[Rainmeter]
Update=2000

[TextStyle]
FontColor=255,255,255,255
FontFace=Trebuchet MS
FontSize=7
AntiAlias=1
NumOfDecimals=0
AccurateText=1
AutoScale=1

; ── PROCESSES ──────────────────────────────────────────────────────────────

[MetermainTEXT]
Meter=String
Text=Processes
AntiAlias=1
FontColor=255,255,255
FontFace=Trebuchet MS
FontSize=7
X=0
Y=0
StringStyle=Bold

[MeasureProcessCount]
Measure=Plugin
Plugin=PerfMon
PerfMonObject=System
PerfMonCounter=Processes
PerfMonDifference=0

[MeterProcessCountTEXT]
Meter=String
meterstyle=textstyle
X=53
Y=0
Text=running
FontFace=Trebuchet MS
FontSize=7
StringStyle=Bold

[MeterProcessCount]
Meter=String
MeasureName=MeasureProcessCount
meterstyle=textstyle
X=101
Y=0
H=200
W=200
Text=%1
FontFace=Trebuchet MS
FontSize=7

; ── SERVICES ───────────────────────────────────────────────────────────────

[MetermainSvcTEXT]
Meter=String
Text=Services
AntiAlias=1
FontColor=255,255,255
FontFace=Trebuchet MS
FontSize=7
X=0
Y=12
StringStyle=Bold

[MeasureServiceCount]
Measure=Plugin
Plugin=ServiceCounter

[MeterServiceCountTEXT]
Meter=String
meterstyle=textstyle
X=53
Y=12
Text=running
FontFace=Trebuchet MS
FontSize=7
StringStyle=Bold

[MeterServiceCount]
Meter=String
MeasureName=MeasureServiceCount
meterstyle=textstyle
X=101
Y=12
H=200
W=200
Text=%1
FontFace=Trebuchet MS
FontSize=7

; ── DRIVERS ────────────────────────────────────────────────────────────────

[MetermainDrvTEXT]
Meter=String
Text=Drivers
AntiAlias=1
FontColor=255,255,255
FontFace=Trebuchet MS
FontSize=7
X=0
Y=24
StringStyle=Bold

[MeasureDriverCount]
Measure=Plugin
Plugin=DriverCounter

[MeterDriverCountTEXT]
Meter=String
meterstyle=textstyle
X=53
Y=24
Text=running
FontFace=Trebuchet MS
FontSize=7
StringStyle=Bold

[MeterDriverCount]
Meter=String
MeasureName=MeasureDriverCount
meterstyle=textstyle
X=101
Y=24
H=200
W=200
Text=%1
FontFace=Trebuchet MS
FontSize=7
